### ISSUE TITLE
filetime 관련 함수 이슈

### ISSUE THREAD

**Issue by llffmmgg** [ChoiJuEon/Assignment2#20]
localtime 함수 특성 때문에 localtime_r 함수 사용해야 할 것 같습니다.

관련 링크
https://codingdog.tistory.com/entry/C%EC%96%B8%EC%96%B4-localtime-%ED%95%A8%EC%88%98-timet-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A5%BC-%ED%98%84%EC%9E%AC-%EB%82%A0%EC%A7%9C%EC%99%80-%EC%8B%9C%EA%B0%84%EC%9C%BC%EB%A1%9C-%EB%B3%80%ED%99%98%ED%95%9C%EB%8B%A4

**Comment by ChoiJuEon** [comment]
제가 이부분 고치겠습니다.

**Comment by llffmmgg** [comment]
수정 후 close
